/**
 * ============================================================
 * fixedDB.js
 * ============================================================
 *
 * Creates the fixed/common tables inside a tenant schema.
 *
 * Example:
 *   await createFixedDashboardTable(client, "org_061");
 *
 * IMPORTANT:
 * - The schema must already exist.
 * - PostgreSQL extension pgvector must already be installed.
 * - This file creates tables only.
 * - It does not create unverified indexes or foreign-key
 *   ON DELETE actions.
 * ============================================================
 */

/**
 * Create all fixed tables for a tenant schema.
 *
 * @param {import("pg").PoolClient} client
 * @param {string} schemaName
 */
export const createFixedDashboardTable = async (client, schemaName) => {
  if (!client) {
    throw new Error("Database client is required");
  }

  if (!schemaName) {
    throw new Error("Schema name is required");
  }

  /*
   * PostgreSQL identifiers cannot be parameterized.
   * We therefore validate the schema name before interpolation.
   *
   * Expected examples:
   *   org_061
   *   org_001
   */
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(schemaName)) {
    throw new Error(`Invalid schema name: ${schemaName}`);
  }

  const schema = `"${schemaName}"`;

  try {
    console.log(
      `\n============================================================`
    );
    console.log(`Creating fixed tables for schema: ${schemaName}`);
    console.log(
      `============================================================`
    );

    /*
     * ==========================================================
     * 1. APARTMENT MEMBER
     * ==========================================================
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.apartment_member (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        security_user_id INTEGER,
        member_code VARCHAR(50),
        first_name VARCHAR(100) NOT NULL,
        last_name VARCHAR(100),
        gender VARCHAR(20),
        date_of_birth DATE,
        mobile_number VARCHAR(20) NOT NULL,
        alternate_mobile_number VARCHAR(20),
        email VARCHAR(255),
        profile_photo TEXT,
        aadhaar_number VARCHAR(20),
        occupation VARCHAR(100),
        apartment_name VARCHAR(255),
        block_tower VARCHAR(100),
        floor_number VARCHAR(20),
        flat_number VARCHAR(50),
        ownership_type VARCHAR(20),
        move_in_date DATE,
        family_member_count INTEGER DEFAULT 0,
        emergency_contact_name VARCHAR(100),
        emergency_contact_relationship VARCHAR(50),
        emergency_contact_mobile VARCHAR(20),
        member_type VARCHAR(30) DEFAULT 'RESIDENT',
        status BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `);

    /*
     * ==========================================================
     * 2. APARTMENT MEMBER FAMILY
     * ==========================================================
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.apartment_member_family (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        member_id INTEGER NOT NULL,
        name VARCHAR(100) NOT NULL,
        relationship VARCHAR(50),
        age INTEGER,
        mobile_number VARCHAR(20),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

        CONSTRAINT fk_apartment_member_family_member
          FOREIGN KEY (member_id)
          REFERENCES ${schema}.apartment_member(id)
      );
    `);

    /*
     * ==========================================================
     * 3. APARTMENT MEMBER VEHICLE
     * ==========================================================
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.apartment_member_vehicle (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        member_id INTEGER NOT NULL,
        vehicle_type VARCHAR(50),
        vehicle_number VARCHAR(50) NOT NULL,
        vehicle_brand VARCHAR(100),
        parking_slot VARCHAR(50),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

        CONSTRAINT fk_apartment_member_vehicle_member
          FOREIGN KEY (member_id)
          REFERENCES ${schema}.apartment_member(id)
      );
    `);

    /*
     * ==========================================================
     * 4. ASSIGN GATES
     * ==========================================================
     *
     * IMPORTANT:
     * id is BIGINT and has NO default according to the
     * supplied information_schema metadata.
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.assign_gates (
        id BIGINT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        status BOOLEAN DEFAULT TRUE,
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP
      );
    `);

    /*
     * ==========================================================
     * 5. FORMS
     * ==========================================================
     *
     * id is GENERATED ALWAYS AS IDENTITY.
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.forms (
        id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        title VARCHAR(255) NOT NULL,
        description VARCHAR(500),
        fields_json JSONB NOT NULL,
        created_by INTEGER,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        layout_columns INTEGER NOT NULL DEFAULT 2
      );
    `);

    /*
     * ==========================================================
     * 6. FORM RESPONSES
     * ==========================================================
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.form_responses (
        id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        form_id INTEGER NOT NULL,
        response_json JSONB NOT NULL,
        submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        submitted_by INTEGER,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        is_draft BOOLEAN NOT NULL DEFAULT FALSE,

        CONSTRAINT fk_form_responses_form
          FOREIGN KEY (form_id)
          REFERENCES ${schema}.forms(id)
      );
    `);

    /*
     * ==========================================================
     * 7. FORM ASSIGNMENTS
     * ==========================================================
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.form_assignments (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        form_id INTEGER NOT NULL,
        member_id INTEGER NOT NULL,
        assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        assigned_by INTEGER,

        CONSTRAINT fk_form_assignments_form
          FOREIGN KEY (form_id)
          REFERENCES ${schema}.forms(id),

        CONSTRAINT fk_form_assignments_member
          FOREIGN KEY (member_id)
          REFERENCES ${schema}.apartment_member(id),

        CONSTRAINT uq_form_assignments_form_member
          UNIQUE (form_id, member_id)
      );
    `);

    /*
     * ==========================================================
     * 8. CAMPAIGNS
     * ==========================================================
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.campaigns (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        campaign_name VARCHAR(255) NOT NULL,
        channel VARCHAR(50) NOT NULL DEFAULT 'Email',
        category VARCHAR(50) DEFAULT 'Others',
        subject VARCHAR(500),
        preheader TEXT,
        status VARCHAR(50) NOT NULL DEFAULT 'Draft',
        scheduled_at TIMESTAMP,
        created_by VARCHAR(50),
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `);

    /*
     * ==========================================================
     * 9. CAMPAIGN BLOCKS
     * ==========================================================
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.campaign_blocks (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        campaign_id INTEGER NOT NULL,
        block_type VARCHAR(50) NOT NULL,
        content JSONB NOT NULL DEFAULT '{}'::jsonb,
        sort_order INTEGER NOT NULL DEFAULT 0,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

        CONSTRAINT fk_campaign_blocks_campaign
          FOREIGN KEY (campaign_id)
          REFERENCES ${schema}.campaigns(id)
      );
    `);

    /*
     * ==========================================================
     * 10. CAMPAIGN DELIVERY LOGS
     * ==========================================================
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.campaign_delivery_logs (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        campaign_id INTEGER NOT NULL,
        sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        total INTEGER NOT NULL DEFAULT 0,
        delivered_count INTEGER NOT NULL DEFAULT 0,
        failed_count INTEGER NOT NULL DEFAULT 0,
        delivered JSONB NOT NULL DEFAULT '[]'::jsonb,
        failed JSONB NOT NULL DEFAULT '[]'::jsonb,
        created_by VARCHAR(50),

        CONSTRAINT fk_campaign_delivery_logs_campaign
          FOREIGN KEY (campaign_id)
          REFERENCES ${schema}.campaigns(id)
      );
    `);

    /*
     * ==========================================================
     * 11. ANNOUNCEMENTS
     * ==========================================================
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.announcements (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        organisation_id INTEGER NOT NULL,
        title VARCHAR(255) NOT NULL,
        message TEXT NOT NULL,
        priority VARCHAR(20) NOT NULL DEFAULT 'Notice',
        created_by INTEGER,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        expires_at DATE,
        is_active BOOLEAN DEFAULT TRUE,
        starts_at DATE
      );
    `);

    /*
     * ==========================================================
     * 12. IMPORTANT INFORMATION
     * ==========================================================
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.important_information (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        organisation_id INTEGER NOT NULL,
        title VARCHAR(255) NOT NULL,
        description TEXT NOT NULL,
        status VARCHAR(20) NOT NULL DEFAULT 'published',
        created_by INTEGER,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        priority VARCHAR(20) DEFAULT 'Important',
        expires_at DATE,
        is_active BOOLEAN DEFAULT TRUE
      );
    `);

    /*
     * ==========================================================
     * 13. QUICK REQUEST TYPES
     * ==========================================================
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.quick_request_types (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        org_id INTEGER NOT NULL,
        request_name VARCHAR(255) NOT NULL,
        description TEXT,
        status VARCHAR(20) DEFAULT 'Active',
        question TEXT,
        question_type VARCHAR(30),
        required BOOLEAN NOT NULL DEFAULT FALSE,
        options JSONB NOT NULL DEFAULT '[]'::jsonb,
        display_order INTEGER NOT NULL DEFAULT 0,
        created_by INTEGER,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        icon VARCHAR(50) DEFAULT 'other',
        is_bookable BOOLEAN DEFAULT FALSE,
        slots JSONB DEFAULT '[]'::jsonb,
        max_bookings_per_slot INTEGER DEFAULT 1,
        booking_mode VARCHAR(20) DEFAULT 'slots',

        CONSTRAINT quick_request_types_question_type_check
          CHECK (
            question_type IS NULL
            OR question_type IN (
              'text',
              'textarea',
              'number',
              'date',
              'dropdown',
              'yesno',
              'attachment'
            )
          ),

        CONSTRAINT quick_request_types_status_check
          CHECK (
            status IN ('Active', 'Inactive')
          )
      );
    `);

    /*
     * ==========================================================
     * 14. QUICK REQUEST RESPONSES
     * ==========================================================
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.quick_request_responses (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        request_type_id INTEGER NOT NULL,
        org_id INTEGER NOT NULL,
        requested_by INTEGER NOT NULL,
        status VARCHAR(20) NOT NULL DEFAULT 'Pending',
        answers JSONB NOT NULL DEFAULT '{}'::jsonb,
        submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        reviewed_by INTEGER,
        reviewed_at TIMESTAMP,
        rejection_reason TEXT,
        approval_comment TEXT,
        announcement TEXT,
        expires_at DATE,
        start_date DATE,

        CONSTRAINT quick_request_responses_status_check
          CHECK (
            status IN ('Pending', 'Approved', 'Rejected')
          ),

        CONSTRAINT fk_quick_request_response_type
          FOREIGN KEY (request_type_id)
          REFERENCES ${schema}.quick_request_types(id)
      );
    `);

    /*
     * ==========================================================
     * 15. VENDORS / SERVICE PROVIDERS
     * ==========================================================
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.vendors_service_providers (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        organisation_id INTEGER NOT NULL,
        category VARCHAR(100) NOT NULL,
        name VARCHAR(255) NOT NULL,
        description TEXT,
        services TEXT,
        rating NUMERIC(3,1) DEFAULT 0,
        review_count INTEGER DEFAULT 0,
        phone VARCHAR(30),
        created_by INTEGER,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        is_active BOOLEAN DEFAULT TRUE,
        recommendation TEXT,
        icon VARCHAR(50)
      );
    `);

    /*
     * ==========================================================
     * 16. PUNCH LOGS
     * ==========================================================
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.punch_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        table_name TEXT NOT NULL,
        user_id BIGINT NOT NULL,
        full_name TEXT,
        distance DOUBLE PRECISION,
        punch_type VARCHAR(10) NOT NULL,
        punch_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        apartment_number VARCHAR(50),
        vehicle_number VARCHAR(20),
        gate_name VARCHAR(255)
      );
    `);

    /*
     * ==========================================================
     * 17. DELIVERY PERSON
     * ==========================================================
     *
     * face_descriptor is public.vector.
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.delivery_person (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        full_name TEXT NOT NULL,
        mobile_number VARCHAR(15) NOT NULL,
        profile_photo TEXT NOT NULL,
        face_descriptor public.vector,
        status TEXT NOT NULL DEFAULT 'Active',
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
      );
    `);

    /*
     * ==========================================================
     * 18. GUEST
     * ==========================================================
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.guest (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        full_name TEXT NOT NULL,
        face_descriptor public.vector,
        status TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
      );
    `);

    /*
     * ==========================================================
     * 19. GANGAVVA
     * ==========================================================
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.gangavva (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        full_name TEXT NOT NULL,
        face_descriptor public.vector
      );
    `);

    /*
     * ==========================================================
     * 20. FACE DETAILS
     * ==========================================================
     */
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${schema}.face_details (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        table_name TEXT NOT NULL,
        record_id BIGINT NOT NULL,
        face_descriptor public.vector NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    /*
     * ==========================================================
     * SAFETY / MIGRATION COLUMNS
     * ==========================================================
     *
     * These are useful because some tenant schemas may have
     * been created before these columns were introduced.
     *
     * CREATE TABLE IF NOT EXISTS does NOT update an existing
     * table, so these statements ensure the newer columns exist.
     * ==========================================================
     */

    await client.query(`
      ALTER TABLE ${schema}.announcements
      ADD COLUMN IF NOT EXISTS starts_at DATE;
    `);

    await client.query(`
      ALTER TABLE ${schema}.announcements
      ADD COLUMN IF NOT EXISTS expires_at DATE;
    `);

    await client.query(`
      ALTER TABLE ${schema}.announcements
      ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
    `);

    await client.query(`
      ALTER TABLE ${schema}.important_information
      ADD COLUMN IF NOT EXISTS priority VARCHAR(20) DEFAULT 'Important';
    `);

    await client.query(`
      ALTER TABLE ${schema}.important_information
      ADD COLUMN IF NOT EXISTS expires_at DATE;
    `);

    await client.query(`
      ALTER TABLE ${schema}.important_information
      ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
    `);

    await client.query(`
      ALTER TABLE ${schema}.vendors_service_providers
      ADD COLUMN IF NOT EXISTS recommendation TEXT;
    `);

    await client.query(`
      ALTER TABLE ${schema}.vendors_service_providers
      ADD COLUMN IF NOT EXISTS icon VARCHAR(50);
    `);

    await client.query(`
      ALTER TABLE ${schema}.quick_request_responses
      ADD COLUMN IF NOT EXISTS start_date DATE;
    `);

    /*
     * ==========================================================
     * DONE
     * ==========================================================
     */

    console.log(
      `✓ Fixed tables created/verified successfully for ${schemaName}`
    );

    return {
      success: true,
      schemaName,
      message: `Fixed tables created/verified successfully for ${schemaName}`,
    };
  } catch (error) {
    console.error(
      `✗ Failed to create fixed tables for ${schemaName}:`,
      error
    );

    throw error;
  }
};

export default createFixedDashboardTable;
